version: "3.5"
services:
  # Install postgres and setup the student database.
  postgres:
    container_name: postgres
    image: postgres
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5432:5432
    environment:
       - POSTGRES_DB=testdb
       - POSTGRES_USER=user
       - POSTGRES_PASSWORD=password