version: "3.5"
services:
  # Install postgres and setup the student database.
  postgres:
    container_name: postgres
    image: postgres
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5432:5432
    environment:
       - POSTGRES_DB=testdb
       - POSTGRES_USER=user
       - POSTGRES_PASSWORD=password
  mq:
    container_name: mq
    image: rabbitmq:3.8-alpine
    ports:
      - "9001:15672"
      - "5672:5672"