version: "3.5"
services:
  postgres:
    container_name: postgres
    image: postgres
    build:
      context: postgres
      dockerfile: postgres.dockerfile
    ports:
      - 5432:5432
    environment:
       - POSTGRES_DB=testdb
       - POSTGRES_USER=user
       - POSTGRES_PASSWORD=password
  mq:
    container_name: mq
    image: mq
    build:
      context: mq
      dockerfile: mq.dockerfile
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "9001:15672"
      - "5672:5672"
  sqs:
    container_name: sqs
    image: sqs
    build:
      context: sqs
      dockerfile: sqs.dockerfile
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "9002:15672"
      - "5673:5672"